manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: elpekenin
      url-base: https://github.com/elpekenin
    - name: urob
      url-base: https://github.com/urob
    - name: AndrewMSHowe
      url-base: https://github.com/AndrewMSHowe
    - name: joelspadin
      url-base: https://github.com/joelspadin
  projects:
    - name: zmk
      import: app/west.yml
      remote: zmkfirmware
      revision: main
    - name: zmk-userspace
      remote: elpekenin
      revision: main
    - name: zmk-helpers
      remote: AndrewMSHowe
      revision: add-rolio46-key-labels
    - name: zmk-leader-key
      remote: urob
      revision: v0.2.1
    - name: zmk-locales
      remote: joelspadin
      revision: main
  self:
    path: config
